### 学习numpy

In [3]:
import numpy as np

In [3]:
a = np.array([-1,-3,-5,1,5,8,9])
a

array([-1, -3, -5,  1,  5,  8,  9])

In [7]:
b = np.abs(a)
display(a,b)


array([-1, -3, -5,  1,  5,  8,  9])

array([1, 3, 5, 1, 5, 8, 9])

In [10]:
# 开平方
b = np.array([1,4,9,16,36,49])
display(np.sqrt(b))

array([1., 2., 3., 4., 6., 7.])

In [12]:
c = np.array([1,2,3])
display(np.square(c))

array([1, 4, 9], dtype=int32)

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([9,8,7,6,5,4,3,2,1])

In [24]:
np.maximum(a,b)
np.minimum(b,a)

array([1, 2, 3, 4, 5, 4, 3, 2, 1])

### WHERE

In [28]:
import numpy as np
nd1  = np.array([1,3,5,7,9])
nd2  = np.array([2,4,6,8,10])
cond = np.array([True,False,False,True,True])

In [30]:
# 如果cond为True就返回nd1中的数据，否则返回nd2中的数据
np.where(cond,nd1,nd2)

array([1, 4, 6, 7, 9])

In [32]:
a = np.random.randint(0,100,size = 50)
display(a)
np.where(a > 50,a, -100)

array([89, 87, 10, 34, 59, 63, 82, 49, 42, 20, 53, 28, 60,  5, 45, 51, 58,
       19, 82, 58, 48, 73, 29, 11, 15, 39, 45, 70, 56, 14, 71, 78, 96, 55,
       70,  6, 62, 30, 48, 33, 15, 84, 17, 29, 17,  1, 99, 39, 78, 36])

array([  89,   87, -100, -100,   59,   63,   82, -100, -100, -100,   53,
       -100,   60, -100, -100,   51,   58, -100,   82,   58, -100,   73,
       -100, -100, -100, -100, -100,   70,   56, -100,   71,   78,   96,
         55,   70, -100,   62, -100, -100, -100, -100,   84, -100, -100,
       -100, -100,   99, -100,   78, -100])

In [39]:
cond = (a >= 50) & (a < 60)
np.where(cond,a+10,a)

array([89, 87, 10, 34, 69, 63, 82, 49, 42, 20, 63, 28, 60,  5, 45, 61, 68,
       19, 82, 68, 48, 73, 29, 11, 15, 39, 45, 70, 66, 14, 71, 78, 96, 65,
       70,  6, 62, 30, 48, 33, 15, 84, 17, 29, 17,  1, 99, 39, 78, 36])

### Sort

In [55]:
a = np.random.randint(0,100,size = 20)
a 

array([53, 45, 46, 44, 85, 60, 71, 97,  3, 22, 92, 98, 56,  4, 82,  9, 43,
       56, 26,  2])

In [43]:
b = np.sort(a)
display(b)

array([ 5, 10, 17, 18, 20, 21, 44, 50, 54, 56, 56, 60, 61, 63, 69, 70, 85,
       86, 96, 99])

In [61]:
a = np.random.randint(0,100,size = 20)
display(a)
index = a.argsort()
display(index)

a[index][::-1]

array([63, 39, 87, 40, 72, 25, 29, 82, 31,  6, 69, 95, 22,  5, 21, 38, 36,
       76, 21, 41])

array([13,  9, 14, 18, 12,  5,  6,  8, 16, 15,  1,  3, 19,  0, 10,  4, 17,
        7,  2, 11], dtype=int64)

array([95, 87, 82, 76, 72, 69, 63, 41, 40, 39, 38, 36, 31, 29, 25, 22, 21,
       21,  6,  5])

### 集合操作

In [66]:
a = np.random.randint(0,30,size = 15)
b = np.random.randint(0,30,size = 15)
display(a,b)

array([21,  0,  4,  1,  4, 20,  9, 13,  7, 18,  5, 23, 14, 26, 15])

array([ 0, 17, 29, 18,  9, 10, 16, 18, 27, 22, 28,  4,  0, 23, 29])

In [64]:
# 交集
np.intersect1d(a,b)

array([ 0,  1,  2,  9, 29])

In [65]:
# 并集
np.union1d(a,b)

array([ 0,  1,  2,  7,  9, 13, 14, 15, 17, 18, 20, 22, 24, 25, 26, 27, 29])

In [68]:
# 差积
np.setdiff1d(a,b)

array([ 1,  5,  7, 13, 14, 15, 20, 21, 26])

### 数学和统计函数

In [4]:
a = np.random.randint(0,100,size = (3,5))
display(a)

array([[87, 77, 32, 67, 57],
       [67, 10, 32, 23, 44],
       [15, 23, 58, 33, 39]])

In [80]:
a.min() # 最小值

1

In [91]:
a.max(axis = 1) # 最大值

array([99, 76, 86])

In [96]:
a.mean() # 平均值

53.666666666666664

In [98]:
np.median(a) # 中位数

64.0

In [99]:
a.sum()

805

In [100]:
a.std() # 标准差

32.277270984738195

In [101]:
a.var() # 方差

1041.8222222222223

In [102]:
a.cumsum() # 累加和

array([ 93,  94, 158, 257, 285, 289, 363, 439, 513, 533, 573, 659, 673,
       754, 805], dtype=int32)

In [103]:
a.cumprod() # 累乘

array([         93,          93,        5952,      589248,    16498944,
          65995776,   588720128,  1793056768,  -457785344,  -565772288,
       -1156055040,  -636485632,  -320864256,  -220200960,  1654652928],
      dtype=int32)

In [109]:
a.argmin() # 返回最小值的索引

7

In [110]:
a.argmax()

13

In [120]:
display(a)
np.argwhere((a>30) | (a<40))

array([[20, 37, 12, 10, 70],
       [30, 76,  9, 84, 68],
       [60, 15, 35, 90, 48]])

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4]], dtype=int64)

In [122]:
np.cov(a) # 协方差

array([[ 618.2 ,  290.85, -238.85],
       [ 290.85, 1044.8 ,  208.95],
       [-238.85,  208.95,  788.3 ]])

In [5]:
display(a)
np.corrcoef(a) # 相关系数

array([[87, 77, 32, 67, 57],
       [67, 10, 32, 23, 44],
       [15, 23, 58, 33, 39]])

array([[ 1.        ,  0.22286818, -0.99815711],
       [ 0.22286818,  1.        , -0.24340155],
       [-0.99815711, -0.24340155,  1.        ]])

### 线性代数

In [7]:
A = np.random.randint(0,10,size = (3,3))
B = np.random.randint(0,10,size = (3,4))
display(A,B)

array([[9, 7, 2],
       [1, 1, 7],
       [3, 3, 4]])

array([[2, 7, 5, 7],
       [6, 3, 1, 1],
       [8, 3, 2, 8]])

In [8]:
A.dot(B) # dot矩阵乘法，点乘

array([[76, 90, 56, 86],
       [64, 31, 20, 64],
       [56, 42, 26, 56]])

In [10]:
np.dot(A,B) # 点乘，模块提供的方法

array([[76, 90, 56, 86],
       [64, 31, 20, 64],
       [56, 42, 26, 56]])

In [11]:
A @ B # @符号，表示矩阵运算

array([[76, 90, 56, 86],
       [64, 31, 20, 64],
       [56, 42, 26, 56]])

### Numpy 分析鸢尾花花萼属性各项指标

In [13]:
iris = np.loadtxt("C:/Users/dreed/Desktop/iris.csv") # 鸢尾花花萼长度
display(iris)

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [16]:
# 排序操作
# iris.sort()
iris_sort = np.sort(iris)
display(iris,iris_sort)

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [18]:
# 去重操作
# iris_sort.unique()
iris_unique = np.unique(iris_sort)
display(iris_sort,iris_unique)

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [21]:
# 求和
# iris_unique.sum()
display(np.sum(iris_unique),iris_unique.sum())

210.39999999999998

210.39999999999998

In [23]:
# 求均值
# iris_unique.mean()
display(np.mean(iris_unique),iris_unique.mean())

6.011428571428571

6.011428571428571

In [24]:
# 求累加和
# iris_unique.cumsum()
display(np.cumsum(iris_unique),iris_unique.cumsum())

array([  4.3,   8.7,  13.2,  17.8,  22.5,  27.3,  32.2,  37.2,  42.3,
        47.5,  52.8,  58.2,  63.7,  69.3,  75. ,  80.8,  86.7,  92.7,
        98.8, 105. , 111.3, 117.7, 124.2, 130.8, 137.5, 144.3, 151.2,
       158.2, 165.3, 172.5, 179.8, 187.2, 194.8, 202.5, 210.4])

array([  4.3,   8.7,  13.2,  17.8,  22.5,  27.3,  32.2,  37.2,  42.3,
        47.5,  52.8,  58.2,  63.7,  69.3,  75. ,  80.8,  86.7,  92.7,
        98.8, 105. , 111.3, 117.7, 124.2, 130.8, 137.5, 144.3, 151.2,
       158.2, 165.3, 172.5, 179.8, 187.2, 194.8, 202.5, 210.4])

In [26]:
# 求累乘
# iris_unique.cumprodm()
display(np.cumprod(iris_unique),iris_unique.cumprod())

array([4.30000000e+00, 1.89200000e+01, 8.51400000e+01, 3.91644000e+02,
       1.84072680e+03, 8.83548864e+03, 4.32938943e+04, 2.16469472e+05,
       1.10399431e+06, 5.74077039e+06, 3.04260831e+07, 1.64300849e+08,
       9.03654667e+08, 5.06046613e+09, 2.88446570e+10, 1.67299010e+11,
       9.87064161e+11, 5.92238497e+12, 3.61265483e+13, 2.23984600e+14,
       1.41110298e+15, 9.03105905e+15, 5.87018838e+16, 3.87432433e+17,
       2.59579730e+18, 1.76514217e+19, 1.21794809e+20, 8.52563666e+20,
       6.05320203e+21, 4.35830546e+22, 3.18156299e+23, 2.35435661e+24,
       1.78931102e+25, 1.37776949e+26, 1.08843790e+27])

array([4.30000000e+00, 1.89200000e+01, 8.51400000e+01, 3.91644000e+02,
       1.84072680e+03, 8.83548864e+03, 4.32938943e+04, 2.16469472e+05,
       1.10399431e+06, 5.74077039e+06, 3.04260831e+07, 1.64300849e+08,
       9.03654667e+08, 5.06046613e+09, 2.88446570e+10, 1.67299010e+11,
       9.87064161e+11, 5.92238497e+12, 3.61265483e+13, 2.23984600e+14,
       1.41110298e+15, 9.03105905e+15, 5.87018838e+16, 3.87432433e+17,
       2.59579730e+18, 1.76514217e+19, 1.21794809e+20, 8.52563666e+20,
       6.05320203e+21, 4.35830546e+22, 3.18156299e+23, 2.35435661e+24,
       1.78931102e+25, 1.37776949e+26, 1.08843790e+27])

In [28]:
# 求中位数
display(np.median(iris_unique))

6.0

In [29]:
# 求方差
np.var(iris_unique)

1.0587265306122449

In [ ]:
# 求标准差
np.std(iris_unique)

In [31]:
# 最大值和最小值
display(np.max(iris_unique),np.min(iris_unique))

7.9

4.3