### pandas的数据结构

In [1]:
import numpy as np
import pandas as pd # Pandas基于Numpy，可以看做是Numpy的升级

#### Series

In [2]:
# Series，Series是一维数组，和Numpy数组不一样。Series多了索引

l = np.array([1,2,3,6,9])

s = pd.Series(l)
display(l,s)

array([1, 2, 3, 6, 9])

0    1
1    2
2    3
3    6
4    9
dtype: int32

In [3]:
si = pd.Series(data = l,index=list("ABCDE"))
display(si)

A    1
B    2
C    3
D    6
E    9
dtype: int32

In [4]:
s1 = pd.Series(data = {'A':1,'B':2,'C':3,'D':4,'E':5})
display(s1)

A    1
B    2
C    3
D    4
E    5
dtype: int64

#### DataFrame

In [5]:
# Series是一维的，功能比较少
# DataFrame是二维的，多个Series公用索引就组成了DataFrame
df1 = pd.DataFrame(data = np.random.randint(0,151,size = (5,5)),index=list("ABCDE"),columns=list("abcde"))
display(df1)

a    b    c    d    e
A  128  126    4  109    2
B   80  147  138   58   86
C    0    1  120  139  109
D   55   54    5   97  128
E   10  119  142   61   65

In [6]:
# 如果传入字典，则：key作为列索引，行索引从0开始
df2 = pd.DataFrame(data = {"A":[1,2,3],"B":[4,5,6],"C":[7,8,9]})
display(df2)

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

### 数据查看

In [7]:
df = pd.DataFrame(data = np.random.randint(0,151,size = (100,3)),columns=["Math","English","Python"])
display(df)

Math  English  Python
0    138       98      75
1      7      117      81
2      6       48      54
3     11       51     142
4     52      135      56
..   ...      ...     ...
95   120       22     128
96   101       19     131
97    42      115      73
98   118       70      49
99    17       36       0

[100 rows x 3 columns]

In [8]:
# 显示图形
df.shape

(100, 3)

In [9]:
# 显示前n行元素，默认 n = 5
df.head()

Math  English  Python
0   138       98      75
1     7      117      81
2     6       48      54
3    11       51     142
4    52      135      56

In [10]:
# 显示后n行元素，默认 n = 5
df.tail()

Math  English  Python
95   120       22     128
96   101       19     131
97    42      115      73
98   118       70      49
99    17       36       0

In [11]:
# 查看数据类型
df.dtypes

Math       int32
English    int32
Python     int32
dtype: object

In [12]:
# 显示详细信息
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     100 non-null    int32
 1   English  100 non-null    int32
 2   Python   100 non-null    int32
dtypes: int32(3)
memory usage: 1.3 KB


In [13]:
# 描述：计数，平均数，标准差，最小资，1/4点，中位数（1/2）点，3/4点，最大值
df.describe()

Math     English      Python
count  100.00000  100.000000  100.000000
mean    79.02000   78.980000   76.400000
std     48.28074   43.648037   42.415692
min      1.00000    2.000000    0.000000
25%     34.75000   41.750000   44.000000
50%     85.50000   81.000000   78.500000
75%    123.00000  118.250000  110.000000
max    150.00000  149.000000  150.000000

In [14]:
# 值，返回的是NumPy数组
df.values

array([[138,  98,  75],
       [  7, 117,  81],
       [  6,  48,  54],
       [ 11,  51, 142],
       [ 52, 135,  56],
       [ 91, 149, 121],
       [146, 112,  12],
       [147, 120,   9],
       [142,  78,  81],
       [131,  86,  60],
       [120, 120,   8],
       [150,  95,  46],
       [ 43,  81,  14],
       [135,  90,  88],
       [ 88, 146,  52],
       [ 37, 137, 118],
       [  2,  29,  99],
       [129,  93,  32],
       [ 96,   7, 106],
       [ 69,  98,   2],
       [128,  52,  84],
       [ 83,  54,  12],
       [ 34,  67,  85],
       [ 23, 130,  96],
       [143, 112, 101],
       [ 19,  75,   6],
       [ 56,  11, 144],
       [ 34, 128,   5],
       [ 78,  24, 110],
       [123,  29, 138],
       [101, 118, 100],
       [150, 122,  44],
       [140,  58,  32],
       [ 42,  41, 116],
       [ 69, 142,  44],
       [ 44,  92, 100],
       [ 75, 146,  67],
       [ 89,   7,  68],
       [ 12, 118,  58],
       [114,  27,  17],
       [136,  28,  76],
       [ 20,   2

In [15]:
# 列索引
df.columns

Index(['Math', 'English', 'Python'], dtype='object')

In [16]:
# 行索引
df.index

RangeIndex(start=0, stop=100, step=1)

### 数据输入与输出

#### CSV 

In [17]:
df = pd.DataFrame(data  = np.random.randint(0,151,size=(100,3)),columns=["Python","Math","En"])
df

Python  Math   En
0       20   108  139
1      138   106   93
2       92    71   36
3       18   150  146
4       11    45   82
..     ...   ...  ...
95     101    24   85
96       3    93    0
97     121   132   42
98      90   130  150
99      71     7   56

[100 rows x 3 columns]

In [18]:
df.to_csv("C:/Users/dreed/Desktop/pandas_data.csv",
          sep = ",", # 保存分隔符
          index = True, # 保存行索引
          header = True # 保存列索引
         )

In [19]:
pd.read_csv("C:/Users/dreed/Desktop/pandas_data.csv",
            index_col=0, # 设置第一列为行索引
            header=0 # 设置第一行为列索引
         
)

Python  Math   En
0       20   108  139
1      138   106   93
2       92    71   36
3       18   150  146
4       11    45   82
..     ...   ...  ...
95     101    24   85
96       3    93    0
97     121   132   42
98      90   130  150
99      71     7   56

[100 rows x 3 columns]

#### Excel

In [20]:
# 导出Excel文件，xls格式需要导入xlwt模块，xlsx格式需要导入openpyxl
df.to_excel("C:/Users/dreed/Desktop/pandas_data.xlsx")

In [21]:
pd.read_excel("C:/Users/dreed/Desktop/pandas_data.xlsx",
    index_col = 0, # 设置行索引
    header = 0 # 设置列索引   
             )

Python  Math   En
0       20   108  139
1      138   106   93
2       92    71   36
3       18   150  146
4       11    45   82
..     ...   ...  ...
95     101    24   85
96       3    93    0
97     121   132   42
98      90   130  150
99      71     7   56

[100 rows x 3 columns]

#### HDF5

In [22]:
# 需要引入tables这个包
df.to_hdf("C:/Users/dreed/Desktop/pandas_data.df5")

TypeError: to_hdf() missing 1 required positional argument: 'key'

#### SQL

### 数据选取

#### 获取数据 

In [ ]:
df = pd.DataFrame(data = np.random.randint(0,151,size = (26,3)),index=list("ABCDEFGHIJKLMNOPQRSTUVWXYZ"),columns = ["Python","Java","Groovy"])
df

In [ ]:
df.Python

In [ ]:
df["Python"]

In [ ]:
df['A'::2]

In [ ]:
df[['Python',"Java"]]

#### 标签获取

In [ ]:
df.loc['A'::2,'Python'::2]

In [ ]:
df.loc[list("ABC"),['Python','Java']]

#### 位置获取

In [ ]:
df.iloc[0::5,1:]

#### boolean索引

In [ ]:
cond = df.Python > 80
df[cond]

In [ ]:
cond = df.mean(axis = 1) > 75
df[cond]

In [ ]:
cond = (df.Python > 80) & (df.Java > 100)
df[cond]

In [ ]:
cond = df.index.isin(list("XYZMNPQ"))
df[cond]

#### 赋值操作

In [ ]:
# 修改对应位置上的数据
df["Python"]["A"] = 150
df

In [ ]:
# 新添加一列
df['Scala'] = np.random.randint(0,151,size = 26)
df

In [ ]:
df.loc[list("ABC"),"Groovy"] = 100
df

In [ ]:
cond = df < 60
df[cond] = 60
df

### 数据集成

#### concat数据串联

In [ ]:
# np.concatenate NumPy数据串联
columns = ["Python","Java","Groovy"]
df1 = pd.DataFrame(np.random.randint(0,151,size = (5,3)),index=list("ABCDE"),columns=columns)
df2 = pd.DataFrame(np.random.randint(0,151,size = (5,3)),index=list("MNXYZ"),columns=columns)
df3 = pd.DataFrame(np.random.randint(0,151,size = (5,2)),index=list("PQIJK"),columns=["Shell","Scala"])
display(df1,df2,df3)

In [ ]:
pd.concat([df1,df2],axis=0)

In [ ]:
pd.concat([df1,df3],axis=1)

#### 数据插入

In [ ]:
# 插入一列数据
df1.insert(loc = 1,column = "C++",value = np.random.randint(0,151,size = 5))
df1

In [ ]:
# 插入行数据
df1.append(df2)

#### JOIN SQL风格合并

In [27]:
df1 = pd.DataFrame(data = {"name":["张三","李四","王五","赵六"],"height":[175,172,169,183]})
df2 = pd.DataFrame(data = {"name":["张三","李四","王五","安康"],"weight":[150,132,90,120]})
df3 = pd.DataFrame(data = {"名字":["张三","李四","王五","安康"],"salary":[12000,18000,8000,30000]})
display(df1,df2,df3)

name  height
0   张三     175
1   李四     172
2   王五     169
3   赵六     183

name  weight
0   张三     150
1   李四     132
2   王五      90
3   安康     120

名字  salary
0  张三   12000
1  李四   18000
2  王五    8000
3  安康   30000

In [28]:
# 根据共同的属性合并数据
# df1 和 df2 共同属性：name
# 数据库，合并join，共同key
pd.merge(df1,df2) 

name  height  weight
0   张三     175     150
1   李四     172     132
2   王五     169      90

In [30]:
# how 设置合并方式：left、right、outer、inner、cross，默认：inner
pd.merge(df1,df2,how="outer") 

name  height  weight
0   张三   175.0   150.0
1   李四   172.0   132.0
2   王五   169.0    90.0
3   赵六   183.0     NaN
4   安康     NaN   120.0

In [39]:
# 指定关联条件
pd.merge(df2,df3,left_on='name',right_on='名字')

name  weight  名字  salary
0   张三     150  张三   12000
1   李四     132  李四   18000
2   王五      90  王五    8000
3   安康     120  安康   30000

In [40]:
df4 = pd.DataFrame(data = np.random.randint(0,151,size = (8,3)),index=list("ABCDEFGH"),columns=["Python","Math","Shell"])
df4

Python  Math  Shell
A     142    67    116
B      73     5    144
C      20    14    150
D      66   106     93
E       6    86    127
F     126    90     45
G     116    48     22
H      22   144    147

In [47]:
score_mean = df4.mean(axis=1).round(2)

df4.insert(loc = df4.shape[1],column="avg_score",value=score_mean)
df4

Python  Math  Shell  avg_score
A     142    67    116     108.33
B      73     5    144      74.00
C      20    14    150      61.33
D      66   106     93      88.33
E       6    86    127      73.00
F     126    90     45      87.00
G     116    48     22      62.00
H      22   144    147     104.33

### 数据清洗

In [62]:
df = pd.DataFrame(data = {"color":["red","green","blue","blue","red",None,np.NaN,"green","blue"],"price":[18,20,22,22,30,15,15,43,57]})
df

color  price
0    red     18
1  green     20
2   blue     22
3   blue     22
4    red     30
5   None     15
6    NaN     15
7  green     43
8   blue     57

In [63]:
# 删除重复数据,NaN和None是一回事
df.drop_duplicates()

color  price
0    red     18
1  green     20
2   blue     22
4    red     30
5   None     15
7  green     43
8   blue     57

In [65]:
# 删除空数据
df.dropna()

color  price
0    red     18
1  green     20
2   blue     22
3   blue     22
4    red     30
7  green     43
8   blue     57

In [67]:
# 删除行
df.drop(index=[0,2,4,6,8])

color  price
1  green     20
3   blue     22
5   None     15
7  green     43

In [68]:
# 删除列
df.drop(columns='price')

color
0    red
1  green
2   blue
3   blue
4    red
5   None
6    NaN
7  green
8   blue

In [76]:
# filter过滤数据
df.filter(items=['color'],axis=1)

color
0    red
1  green
2   blue
3   blue
4    red
5   None
6    NaN
7  green
8   blue

In [77]:
df['size'] = 1024 # 广播
df

color  price  size
0    red     18  1024
1  green     20  1024
2   blue     22  1024
3   blue     22  1024
4    red     30  1024
5   None     15  1024
6    NaN     15  1024
7  green     43  1024
8   blue     57  1024

In [78]:
# 模糊匹配，保留带i的列
df.filter(like='i')

price  size
0     18  1024
1     20  1024
2     22  1024
3     22  1024
4     30  1024
5     15  1024
6     15  1024
7     43  1024
8     57  1024

In [84]:
# 使用正则表达式过滤
df.filter(regex="r$")

color
0    red
1  green
2   blue
3   blue
4    red
5   None
6    NaN
7  green
8   blue

In [87]:
# 异常值过滤
a = np.random.randint(0,1000,size = 200)
display(a)
cond = (a <= 800) & (a >= 100)
a[cond]

array([231, 441, 517, 256, 509, 948, 425, 532, 303, 151, 740, 489, 934,
       871,  96, 386, 449, 320, 733, 810, 621, 141,  57, 911, 566,  93,
       174, 624, 807,   8, 488, 346, 347, 845,  27, 320, 174, 725, 957,
       856, 500, 325, 863,  13, 332,  36, 694, 341,  27, 996, 567, 699,
       120, 387, 201, 667, 984, 662, 643, 532, 329, 252,  10,  37, 861,
       601, 603, 939, 706, 376, 713, 983, 727, 102, 859, 717, 902, 792,
       843,  45,  87, 956, 952, 474, 810, 659, 687,  62, 219, 804, 836,
       977, 989, 656, 188, 798, 898, 460, 767, 655, 188,  32, 659, 141,
       887, 111, 497, 288, 621,  67, 327, 495, 453, 728,  57, 394, 330,
       524, 824, 613, 168, 506, 374, 476, 950, 189, 416, 425, 981, 167,
       862, 684,  88, 878, 793, 898, 917, 807, 568, 901, 317, 145, 318,
       526, 251, 556, 584, 361, 254, 860, 748, 533, 859, 232, 569, 531,
       285, 493, 757, 569, 810, 681, 972, 695, 531, 524, 618, 296, 587,
        95,  34, 876, 905, 889, 702,   5, 779, 921, 553, 747, 16

In [99]:
# 正态分布，平均值：0，标准差：1
b = np.random.randn(10000)
b

array([-0.30464382, -0.29654891,  1.04539397, ..., -0.81554092,
        0.171212  ,  0.06652104])

In [100]:
cond = np.abs(b) > 3 * 1
b[cond]

array([ 3.05621079, -3.0075269 , -3.4715351 , -3.27070932, -3.23892104,
        3.58012179, -3.04641976, -3.60188761,  3.13624873, -3.15783445,
       -3.9947863 , -3.89345421, -3.37100799,  3.07886013,  3.2257467 ,
        3.35993377, -3.12282983, -3.05577328, -3.00887825,  3.01853582,
        3.01986169, -3.14495397,  3.27057049, -3.00286901, -3.32156912,
       -3.14195422,  3.04886951])

### 数据转换

#### 轴和袁术转换

In [106]:
df = pd.DataFrame(data = np.random.randint(1,10,size = (10,3)),columns = ["Python","Java","Groovy"],index = list("ABCDEFGHIJ"))
df

Python  Java  Groovy
A       9     2       4
B       3     1       1
C       2     4       3
D       5     9       3
E       8     7       5
F       9     3       3
G       1     6       3
H       9     7       8
I       6     7       1
J       8     2       9

In [107]:
df.rename(index = {'A':'X','B':'Y','C':'Z'},columns={'Python':'人工智能','Java':'大数据'})

人工智能  大数据  Groovy
X     9    2       4
Y     3    1       1
Z     2    4       3
D     5    9       3
E     8    7       5
F     9    3       3
G     1    6       3
H     9    7       8
I     6    7       1
J     8    2       9

In [110]:
df.replace({9:10})

Python  Java  Groovy
A      10     2       4
B       3     1       1
C       2     4       3
D       5    10       3
E       8     7       5
F      10     3       3
G       1     6       3
H      10     7       8
I       6     7       1
J       8     2      10

In [111]:
df.replace({'Groovy':3},-3)

Python  Java  Groovy
A       9     2       4
B       3     1       1
C       2     4      -3
D       5     9      -3
E       8     7       5
F       9     3      -3
G       1     6      -3
H       9     7       8
I       6     7       1
J       8     2       9

#### map映射元素

In [114]:
# map只能针对一列操作，即：Series。没有映射的值都会转为NaN
df['Python'].map({9:90,3:30})

A    90.0
B    30.0
C     NaN
D     NaN
E     NaN
F    90.0
G     NaN
H    90.0
I     NaN
J     NaN
Name: Python, dtype: float64

In [115]:
df['Java'].map(lambda x:x ** 2)

A     4
B     1
C    16
D    81
E    49
F     9
G    36
H    49
I    49
J     4
Name: Java, dtype: int64

In [116]:
def convert(x:int) -> int:
    return x ** 3
df.Groovy.map(convert)

A     64
B      1
C     27
D     27
E    125
F     27
G     27
H    512
I      1
J    729
Name: Groovy, dtype: int64

#### apply映射元素转变

In [121]:
# apply既可以修改Series又可以修改DataFrame
# apply针对列进行修改
df.Python.apply(lambda x : x * 2)

A    18
B     6
C     4
D    10
E    16
F    18
G     2
H    18
I    12
J    16
Name: Python, dtype: int64

In [122]:
# apply针对ataFrame进行修改
df.apply(lambda x : x * 2)

Python  Java  Groovy
A      18     4       8
B       6     2       2
C       4     8       6
D      10    18       6
E      16    14      10
F      18     6       6
G       2    12       6
H      18    14      16
I      12    14       2
J      16     4      18

#### transform元素转变

In [124]:
# transform和apply用法类似
df.transform(lambda x : x * 3)

Python  Java  Groovy
A      27     6      12
B       9     3       3
C       6    12       9
D      15    27       9
E      24    21      15
F      27     9       9
G       3    18       9
H      27    21      24
I      18    21       3
J      24     6      27

#### 重排随机抽样哑变量

In [129]:
# 返回乱序的随机数据
index = np.random.permutation(10)
index

array([4, 8, 6, 7, 2, 3, 1, 5, 0, 9])

In [130]:
# 重排，将索引顺序打乱
df.take(index)

Python  Java  Groovy
E       8     7       5
I       6     7       1
G       1     6       3
H       9     7       8
C       2     4       3
D       5     9       3
B       3     1       1
F       9     3       3
A       9     2       4
J       8     2       9

In [134]:
# 随机抽样数据
index = np.random.permutation(10)

df.take(np.random.permutation(10)).tail(3)

Python  Java  Groovy
A       9     2       4
G       1     6       3
H       9     7       8

In [137]:
# 哑变量数据准备
df = pd.DataFrame(data={'key':list('ababcbc')})
df

key
0   a
1   b
2   a
3   b
4   c
5   b
6   c

In [141]:
# 哑变量 - one-hot
pd.get_dummies(df,prefix='',prefix_sep='')

a  b  c
0  1  0  0
1  0  1  0
2  1  0  0
3  0  1  0
4  0  0  1
5  0  1  0
6  0  0  1

In [142]:
df = pd.DataFrame(data={"A":list('ababcbc'),"B":list('xyxyzyz')})
df

A  B
0  a  x
1  b  y
2  a  x
3  b  y
4  c  z
5  b  y
6  c  z

In [143]:
pd.get_dummies(df)

A_a  A_b  A_c  B_x  B_y  B_z
0    1    0    0    1    0    0
1    0    1    0    0    1    0
2    1    0    0    1    0    0
3    0    1    0    0    1    0
4    0    0    1    0    0    1
5    0    1    0    0    1    0
6    0    0    1    0    0    1

### 数据重塑

In [144]:
df

A  B
0  a  x
1  b  y
2  a  x
3  b  y
4  c  z
5  b  y
6  c  z

In [145]:
df.T

0  1  2  3  4  5  6
A  a  b  a  b  c  b  c
B  x  y  x  y  z  y  z

In [168]:
df2 = pd.DataFrame(data = np.random.randint(0,10,size = (30,3)),columns=['Python','Java','Groovy'],index = pd.MultiIndex.from_product([list("ABCDEGHIJK"),list("XYZ")]))
df2

Python  Java  Groovy
A X       2     8       1
  Y       0     6       6
  Z       9     7       6
B X       1     8       2
  Y       4     7       3
  Z       5     3       1
C X       2     0       0
  Y       4     5       9
  Z       0     1       6
D X       6     1       3
  Y       1     3       5
  Z       3     4       7
E X       6     4       6
  Y       6     7       0
  Z       5     0       8
G X       8     1       9
  Y       8     9       8
  Z       7     5       9
H X       7     3       7
  Y       2     0       2
  Z       9     0       1
I X       3     6       9
  Y       6     9       9
  Z       9     2       1
J X       8     6       0
  Y       1     0       3
  Z       2     8       8
K X       8     2       6
  Y       3     7       5
  Z       5     9       1

In [169]:
# unstack将行索引转变为列索引，level表示层级，默认：-1表示最后一层，层次是从外往里数的
df2.unstack(level = 1)

Python       Java       Groovy      
       X  Y  Z    X  Y  Z      X  Y  Z
A      2  0  9    8  6  7      1  6  6
B      1  4  5    8  7  3      2  3  1
C      2  4  0    0  5  1      0  9  6
D      6  1  3    1  3  4      3  5  7
E      6  6  5    4  7  0      6  0  8
G      8  8  7    1  9  5      9  8  9
H      7  2  9    3  0  0      7  2  1
I      3  6  9    6  9  2      9  9  1
J      8  1  2    6  0  8      0  3  8
K      8  3  5    2  7  9      6  5  1

In [170]:
# stack将列索引转变为行索引
df2.stack()

A  X  Python    2
      Java      8
      Groovy    1
   Y  Python    0
      Java      6
               ..
K  Y  Java      7
      Groovy    5
   Z  Python    5
      Java      9
      Groovy    1
Length: 90, dtype: int32

In [172]:
display(df2.unstack(level=1).stack(level = 0),df2.unstack(level=0).stack(level = 0))

X  Y  Z
A Groovy  1  6  6
  Java    8  6  7
  Python  2  0  9
B Groovy  2  3  1
  Java    8  7  3
  Python  1  4  5
C Groovy  0  9  6
  Java    0  5  1
  Python  2  4  0
D Groovy  3  5  7
  Java    1  3  4
  Python  6  1  3
E Groovy  6  0  8
  Java    4  7  0
  Python  6  6  5
G Groovy  9  8  9
  Java    1  9  5
  Python  8  8  7
H Groovy  7  2  1
  Java    3  0  0
  Python  7  2  9
I Groovy  9  9  1
  Java    6  9  2
  Python  3  6  9
J Groovy  0  3  8
  Java    6  0  8
  Python  8  1  2
K Groovy  6  5  1
  Java    2  7  9
  Python  8  3  5

A  B  C  D  E  G  H  I  J  K
X Groovy  1  2  0  3  6  9  7  9  0  6
  Java    8  8  0  1  4  1  3  6  6  2
  Python  2  1  2  6  6  8  7  3  8  8
Y Groovy  6  3  9  5  0  8  2  9  3  5
  Java    6  7  5  3  7  9  0  9  0  7
  Python  0  4  4  1  6  8  2  6  1  3
Z Groovy  6  1  6  7  8  9  1  1  8  1
  Java    7  3  1  4  0  5  0  2  8  9
  Python  9  5  0  3  5  7  9  9  2  5

In [ ]:
df2.mean(axis=1,level=0)

Python  Java  Groovy
A X       2     8       1
  Y       0     6       6
  Z       9     7       6
B X       1     8       2
  Y       4     7       3
  Z       5     3       1
C X       2     0       0
  Y       4     5       9
  Z       0     1       6
D X       6     1       3
  Y       1     3       5
  Z       3     4       7
E X       6     4       6
  Y       6     7       0
  Z       5     0       8
G X       8     1       9
  Y       8     9       8
  Z       7     5       9
H X       7     3       7
  Y       2     0       2
  Z       9     0       1
I X       3     6       9
  Y       6     9       9
  Z       9     2       1
J X       8     6       0
  Y       1     0       3
  Z       2     8       8
K X       8     2       6
  Y       3     7       5
  Z       5     9       1